archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "dnote_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'dnote-{{ .Version }}-checksums.txt'

builds:
-
  binary: dnote
  ldflags:
    - -X main.apiEndpoint={{ .Env.API_ENDPOINT }} -X main.versionTag={{ .Version }}
  goos:
    - darwin
    - linux
    - windows
    - openbsd
  goarch:
    - amd64
    - 386

brew:
  name: dnote
  folder: Formula
  github:
    owner: dnote
    name: homebrew-dnote
  commit_author:
    name: sungwoncho
    email: mikeswcho@gmail.com
  homepage: https://dnote.io
  description: Capture your learning without leaving the command line
  dependencies:
    - go
    - dep
  install: |
    ENV["GOPATH"] = buildpath

    (buildpath/"src/github.com/dnote/cli").install buildpath.children
    cd "src/github.com/dnote/cli" do
      system "dep", "ensure"
      system "go", "build", "-ldflags", "-X main.apiEndpoint=https://api.dnote.io", "-o", bin/"dnote"
    end
  test: |
    system "${bin}/dnote --version"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^refactor:'
