archive:
  format: binary
  name_template: "dnote-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'dnote-{{ .Version }}-checksums.txt'

builds:
-
  binary: dnote
  ldflags:
    - -X core.Version={{.Version}}
    - -X main.apiEndpoint=https://api.dnote.io
  goos:
    - darwin
    - linux
    - windows
    - openbsd
  goarch:
    - amd64
    - 386

brew:
  github:
    owner: dnote
    name: homebrew-dnote
  commit_author:
    name: sungwoncho
    email: mikeswcho@gmail.com
  homepage: https://dnote.io
  description: Capture your learning without leaving the command line

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^refactor:'
