language: go
dist: xenial

go:
  - 1.13

env:
  - NODE_VERSION=10.15.0
    YARN_VERSION=1.19.1-1

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

    # install yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn="$YARN_VERSION"

  - nvm install "$NODE_VERSION"
  - nvm use "$NODE_VERSION"
  - node --version
  - psql -c "CREATE DATABASE dnote_test;" -U postgres

cache:
  yarn: true

install:
  - make install

script:
  - make lint
  - make test-cli
  - make test-api
  - make test-web
  - make test-jslib
